using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace App.Services.Dtos.Common
{
    public enum ErrorCodeType
    {
        Error = 1,
        Validation = 2,
        GoogleTimeZoneApi = 3,
        GoogleGeocodingApi = 4,
        EventNotFound = 5,
        InvalidMessageId = 6,
        InvalidLabel = 7,
        InvalidMessageTemplateType = 8,
        InvalidTemplateId = 9,
        InvalidNotificationTypeId = 10,
        InvalidMemberId = 11,
        InvalidNetworkId = 12,
        InvalidNetworkDescription = 13,
        InvalidWebsiteUrl = 14,
        InvalidWebsiteUrlBase = 15,
        InvalidExtraInfo = 16,
        InvalidVersion = 17,
        InvalidTimeZone = 18,
        InvalidAddress = 19,
        InvalidComment = 20,
        InvalidOwner = 21,
        InvalidContentSummary = 22,
        InvalidStartDate = 23,
        InvalidEndDate = 24,
        InvalidTitle = 25,
        InvalidDescription = 26,
        InvalidPhotoLrgId = 27,
        InvalidRsvpDate = 28,
        InvalidMaxAttending = 29,
        InvalidEventInvites = 30,
        NoPermission = 31,
        NoAccessData = 32,
        NoEventShowComments = 33,
        EventEnded = 34,
        InvalidEventInviteStatus = 35,
        SameEventInviteStatus = 36,
        EventCannotRsvp = 37,
        EventIsFull = 38,
        EventInviteNotFound = 39,
        EventCannotCancel = 40,
        EventCannotDelete = 41,
        MaxAttendingLessThanEventInvites = 42,
        InvalidAccountName = 45,
        InvalidAccountNo = 46,
        InvalidBSB = 47,
        InvalidBankName = 48,
        MissingBankPwdSet = 49,
        InvalidBankPwd = 50,
        InvalidPwd = 51,
        MissingBankId = 52,
        InvalidBankId = 53,
        InvalidContactAddress = 54,
        InvalidEmail = 55,
        InvalidPhone = 56,
        NoPermissionForPrivateFields = 57,
        CannotUpdateMemberContactSummaryUserExist = 58,
        CannotUpdateMemberPersonalInfoUserExist = 59,
        CanNotShare = 60,
        InvalidPostCode = 61,
        InvalidFax = 62,
        InvalidState = 63,
        InvalidSuburb = 64,
        InvalidCity = 65,
        InvalidGuid = 66,
    }
}
